-- OBSOLETO: não execute este arquivo em produção.
--
-- A política anterior permitia que qualquer usuário autenticado acessasse as
-- transações de todos os professores. Execute user_data_rls.sql, que aplica
-- isolamento por user_id a todas as tabelas do aplicativo.
